### ISSUE TITLE
problem: wiki doc is out of date

### ISSUE THREAD

**Issue by amateur-professional** [csirtgadgets/bearded-avenger-sdk-py#57]
Trying to utilize the SDK according to the example set out in the Wiki. My current code is as follows:

```
#!/usr/bin/env python
import os
import sys
import requests
from cifsdk.client import Client
from pprint import pprint
from datetime import datetime, timedelta

prevtime = datetime.utcnow() - timedelta(hours = 1)

client = Client(token='1fba225123d4cbaf574382660cccaac74e815a64dbd74e10af16517a3a061565e77007847544711e',
                remote='http://localhost:5000',
                verify_ssl=False)

itypes = ["fqdn", "url", "md5", "ipv4", "ipv6"]
for type in itypes:
    filters = {
        "itype": type,
        "columns": "indicator,description,additional_data,confidence,provider",
        "reporttime": prevtime
        }
    res = client.indicators_search(filters=filters)

    pprint(res)
```
However, this gives me the following error:
```
Traceback (most recent call last):
  File "<redacted>", line 16, in <module>
    res = cli.indicators_search(filters=filters)
AttributeError: 'Client' object has no attribute 'indicators_search'
```
Considering this is the example used in the wiki I could use some help here. I've inspected the source and the method is definitely there. Really no idea why this is throwing an error.

**Comment by wesyoung** [comment]
looks like the doc needs a bit of work (and maybe the sdk)

as a quick work-around change:

`from cifsdk.client import Client`

to 

`from cifsdk.client.http import HTTP as Client`

i'm gonna leave this open so i don't forget to clean it up.

**Comment by wesyoung** [comment]
i also updated the wiki:

https://github.com/csirtgadgets/bearded-avenger-sdk-py/wiki/Home/_compare/7411fbe51eab09be7c1f1ffcd4fb1ad782f067ff...5f5895fddb32012d8e938138f5e6875cc8825ec1

ty!

**Comment by amateur-professional** [comment]
No problem... while you're doing some documentation maybe you could expand on how the filters work? I seem to be using reporttime incorrectly (I don't have my updated code on hand but I am formatting it as specified [here](https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/REST-API) with strftime and still getting results from outside 1 hour.

**Comment by wesyoung** [comment]
sure thing, are you using sqlite or elasticsearch? i'm assuming you're re-formatting `prevtime = datetime.utcnow() - timedelta(hours = 1)` as your 'updated code' ? are you also accounting for the fact that the results are UTC? and you're suggesting that "there are reporttime" timestamps outside of the last hour 'UTC'"?

**Comment by amateur-professional** [comment]
My "1 hour ago" timestamp is formatted like this: 
`prevtime = (datetime.utcnow() - timedelta(hours = 1)).strftime('%Y-%m-%dT%H:%M:%SZ')`

I'm using whatever the default backend is which I think is elasticsearch. That datetime command should give me UTC time, so yes, I am accounting for that. This client query is giving me results outside of the time range I want - I'm getting results from back in May.

**Comment by amateur-professional** [comment]
If it matters at all, I am actually running with Docker, which doesn't appear to have been updated since 3.0.0a13. I can rotate to the DeploymentKit if Docker is no longer supported.

**Comment by wesyoung** [comment]
ahh, the docker instance was a contribution that's sort of fallen back a bit. i wanna say we actually fixed some reporttime stuff recently too. see if you can re-create the problem in a21 which is the latest release. maybe once things settle someone can help update the docker image with the newer stuff.

**Comment by amateur-professional** [comment]
Ha. Well, I'm trying to, but now the deployment kit does not appear to be setting CIF_ENABLE_INSTALL envvar correctly so the playbook is failing on the last task. I'll raise the relevant issue on that project.

**Comment by wesyoung** [comment]
gah, that was fixed in a21, forgot to tag it in the deployment kit

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/releases/tag/3.0.0a4
https://github.com/csirtgadgets/bearded-avenger/releases/tag/3.0.0a21

**Comment by amateur-professional** [comment]
Woohoo, it looks like reporttime is now working now that I'm on a21!
