### ISSUE TITLE
Submit function not working

### ISSUE THREAD

**Issue by nobbyhegel** [csirtgadgets/bearded-avenger-sdk-py#60]
Trying to automate the submission of a large file of IOCs. Have it working using the Octospice version but there does not seem to be a submit function defined for bearded despite the submit example posted online calling such a function. Has anybody else encountered such a function?

# code goes something like this - I've checked with Octo and works fine
from cifsdk.client.http import HTTP as Client
cli = Client(token='', remote='https://192.168.1.10',
             verify_ssl=False, nowait=True)

data =  = {"observable": "1.1.1.1",
             "lasttime": time_stamp,
             "tags": ["malicious"],
             "confidence": "90",
             "group": "everyone",
             "otype": "ipv4",
             "provider": "test",
             "application": "http",
             "portlist": "80",
             "tlp":"amber"}
 
ret = cli.submit(data)

AttributeError: 'HTTP' object has no attribute 'submit'

**Comment by wesyoung** [comment]
- what version of the client are you running?
- does the client `--submit` flag give you the expected results?
- what doc [or code] where you reading that had you do this `from cifsdk.client.http import HTTP as Client`

maybe  doc bug somewhere..

see:

https://github.com/csirtgadgets/cif-sdk-py/blob/master/cifsdk/client.py#L39
https://github.com/csirtgadgets/cif-sdk-py/blob/master/cifsdk/client.py#L351
https://github.com/csirtgadgets/cif-sdk-py/blob/master/cifsdk/client.py#L509

(this is really messy in v2, spent some time cleaning in v3)

**Comment by wesyoung** [comment]
also see this:

https://github.com/csirtgadgets/bearded-avenger-sdk-py/issues/57

maybe that's what you're running into... (and i need to re-check that issue)
