### ISSUE TITLE
Issue with submitting indicators using sdk

### ISSUE THREAD

**Issue by tembler** [csirtgadgets/bearded-avenger-sdk-py#7]
There seems to be an issue when submitting indicators using the bearded avenger sdk. I found the error to be within "cifsdk/client/__init__.py" the following code references a class function which is not present in the HTTP class

`    elif options.get("submit"):
        logger.info("submitting {0}".format(options.get("submit")))

        rv = cli.submit(indicator=args.indicator, tags=args.tags) ` 

In http.py there is no submit function, I assume this is supposed to be referencing the indicators_search function:

`    def indicators_create(self, data):
        data = str(data)

        uri = "{0}/indicators".format(self.remote)
        self.logger.debug(uri)
        rv = self._post(uri, data)
        return rv["data"] `

I tried to make a few changes while debugging, but ultimately did not get to a solution. Maybe you guys can provide some insight.

**Comment by wesyoung** [comment]
sorry, somehow i missed this. we changed from .submit to .indicators_create, managed to miss that with the --submit arg. fixed. ty!
